services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data

  db_ui:
    image: shyim/adminerevo
    ports:
      - target: 8080
        published: 8000
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_DB: ecommerce
      ADMINER_DEFAULT_USER: root
      ADMINER_DEFAULT_PASSWORD: root
      ADMINER_DESIGN: dracula

volumes:
  data:
